//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoreWpfLocDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCoreWpfLocDemo.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;targetLanguage&quot;: &quot;en-US&quot;,
        ///	&quot;author&quot;: &quot;Test WPF Translation&quot;,
        ///	&quot;description&quot;: &quot;No description&quot;,
        ///	&quot;fileName&quot;: &quot;MainWindow Translation&quot;,
        ///	&quot;objects&quot;: {
        ///		&quot;default&quot;:{
        ///
        ///		},
        ///		&quot;MainWindow&quot;: {
        ///			&quot;button1.text&quot;: &quot;Click me!&quot;,
        ///			&quot;button2.text&quot;: &quot;Restore&quot;,
        ///			&quot;menu.file&quot;: &quot;_File&quot;,
        ///			&quot;menu.file.new&quot; : &quot;_New&quot;,
        ///			&quot;menu.file.open&quot;: &quot;_Open&quot;,
        ///			&quot;menu.file.save&quot;: &quot;_Save&quot;,
        ///			&quot;menu.file.exit&quot;: &quot;E_xit&quot;
        ///		},
        ///		&quot;namespace2&quot;: {
        ///			&quot;translateObj1&quot;: &quot;text1&quot;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;targetLanguage&quot;: &quot;zh-cn&quot;,
        ///	&quot;author&quot;: &quot;Test WPF Translation&quot;,
        ///	&quot;description&quot;: &quot;No description&quot;,
        ///	&quot;fileName&quot;: &quot;MainWindow Translation&quot;,
        ///	&quot;objects&quot;: {
        ///		&quot;default&quot;:{
        ///
        ///		},
        ///		&quot;MainWindow&quot;: {
        ///			&quot;button1.text&quot;: &quot;点击我!&quot;,
        ///			&quot;button2.text&quot;: &quot;还原&quot;,
        ///			&quot;menu.file&quot;: &quot;文件(_F)&quot;,
        ///			&quot;menu.file.new&quot; : &quot;新建(_N)&quot;,
        ///			&quot;menu.file.open&quot;: &quot;打开(_O)&quot;,
        ///			&quot;menu.file.save&quot;: &quot;保存(_S)&quot;,
        ///			&quot;menu.file.exit&quot;: &quot;退出(_X)&quot;
        ///		},
        ///		&quot;namespace2&quot;: {
        ///			&quot;translateObj1&quot;: &quot;text1&quot;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
    }
}
