//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoreWinFormLocDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCoreWinFormLocDemo.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;targetLanguage&quot;: &quot;en-US&quot;,
        ///	&quot;author&quot;: &quot;Test WinForm Translation&quot;,
        ///	&quot;description&quot;: &quot;No description&quot;,
        ///	&quot;fileName&quot;: &quot;Test WinForm Translation&quot;,
        ///	&quot;objects&quot;: {
        ///		&quot;default&quot;:{
        ///		},
        ///		&quot;TestForm&quot;: {
        ///			&quot;button1.text&quot;: &quot;Click me!&quot;,
        ///			&quot;menu.file&quot;: &quot;&amp;File&quot;,
        ///			&quot;menu.file.new&quot;: &quot;&amp;New&quot;,
        ///			&quot;menu.file.open&quot;: &quot;&amp;Open&quot;,
        ///			&quot;menu.file.save&quot;: &quot;&amp;Save&quot;,
        ///			&quot;menu.file.saveAs&quot;: &quot;Save &amp;As&quot;,
        ///			&quot;menu.file.print&quot;: &quot;&amp;Print&quot;,
        ///			&quot;menu.file.printPreview&quot;: &quot;Print Pre&amp;view&quot;,
        ///			&quot;menu.file.exit&quot;:  &quot;E&amp;xit&quot;,
        ///			&quot;menu.ed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;targetLanguage&quot;: &quot;zh-cn&quot;,
        ///	&quot;author&quot;: &quot;Test WinForm Translation&quot;,
        ///	&quot;description&quot;: &quot;No description&quot;,
        ///	&quot;fileName&quot;: &quot;Test WinForm Translation&quot;,
        ///	&quot;objects&quot;: {
        ///		&quot;default&quot;:{
        ///		},
        ///		&quot;TestForm&quot;: {
        ///			&quot;button1.text&quot;: &quot;点击我!&quot;,
        ///			&quot;button2.text&quot;: &quot;还原&quot;,
        ///			&quot;menu.file&quot;: &quot;文件(&amp;F)&quot;,
        ///			&quot;menu.file.new&quot;: &quot;新建文档(&amp;N)&quot;,
        ///			&quot;menu.file.open&quot;: &quot;打开(&amp;O)&quot;,
        ///			&quot;menu.file.save&quot;: &quot;保存(&amp;S)&quot;,
        ///			&quot;menu.file.saveAs&quot;: &quot;另存为(&amp;A)&quot;,
        ///			&quot;menu.file.print&quot;: &quot;打印(&amp;P)&quot;,
        ///			&quot;menu.file.printPreview&quot;: &quot;打印预览(&amp;V)&quot;,
        ///			&quot;menu.file.exit&quot;:   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
    }
}
